### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghost** [jfcg/butter#1]
Hi,
Im trying to use the NewLowPass1 filter and im getting a panic, any ideas ?

    dt := 1. / 44101              // 44100 hz sample rate
    wc := 2 * math.Pi * 600000000 * dt // 600mhz hz cutoff
    filter := butter.NewLowPass1(wc)

for .....
            filteredSample := filter.Next(sample_fl64) // Panics here
.......

Thanks

**Comment by jfcg** [comment]
Cutoff must be less than half of sample rate due to [sampling theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem). Also readme says:
```
All New*() functions return nil if parameters are invalid
```
That cutoff is extrmely high, there is probaly some typo somewhere. You probably wanted to have a cutoff of 6 khz or 600 hz.
